name: My First Workflow

on: [push]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print name
        run: echo "My name is vineet" 

      - name: Print date
        run: date
      - name: Print current branch
        run: echo "Current branch is ${{ github.ref }}"   

  greet:
    runs-on: ubuntu-latest
    needs: say_hello
    steps:
      - name: Greeting step 
        run: echo "Helloe from second job"        
  
  godbye:
    runs-on: ubuntu-latest
    needs: greet
    steps:
      - name: Goodbye step
        run: echo "Goodbye from third job"